/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#ifndef LEGEND_API
#define LEGEND_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern LEGEND_API FName LEGEND_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY


class LEGEND_API ADynamicBlockingVolume : public ABlockingVolume
{
public:
    DECLARE_FUNCTION(execSetFaces);
    DECLARE_CLASS(ADynamicBlockingVolume,ABlockingVolume,0,Legend)
    NO_DEFAULT_CONSTRUCTOR(ADynamicBlockingVolume)
};


class LEGEND_API ABreakableItem : public ADecoration
{
public:
    class UMesh* BrokenMesh;
    class UStaticMesh* BrokenStaticMesh;
    class USound* BreakSound;
    class AParticleGenerator* BreakParticleEffectsRefs[6];
    BITFIELD bDestroyCollision:1 GCC_PACK(4);
    FLOAT DamageAmount GCC_PACK(4);
    FLOAT DamageRadius;
    class UClass* DamageType;
    FLOAT Momentum;
    BITFIELD bShakeView:1 GCC_PACK(4);
    FLOAT Duration GCC_PACK(4);
    FLOAT ShakeMagnitude;
    FLOAT BaseTossMagnitude;
    FLOAT Radius;
    BITFIELD bTossNPCs:1 GCC_PACK(4);
    BITFIELD bTossPCs:1;
    FLOAT MaxTossedMass GCC_PACK(4);
    FLOAT TimeBetweenShakes;
    FStringNoInit AmbientSoundStr;
    FStringNoInit ShakeSoundStr;
    INT InitialHealth;
    DECLARE_CLASS(ABreakableItem,ADecoration,0,Legend)
    NO_DEFAULT_CONSTRUCTOR(ABreakableItem)
};

#endif

AUTOGENERATE_FUNCTION(ADynamicBlockingVolume,-1,execSetFaces);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif

#if __STATIC_LINK
#ifndef LEGEND_NATIVE_DEFS
#define LEGEND_NATIVE_DEFS

DECLARE_NATIVE_TYPE(Legend,ADynamicBlockingVolume);
DECLARE_NATIVE_TYPE(Legend,ABreakableItem);

#define AUTO_INITIALIZE_REGISTRANTS_LEGEND \
	ADynamicBlockingVolume::StaticClass(); \
	GNativeLookupFuncs[Lookup++] = &FindLegendADynamicBlockingVolumeNative; \
	ABreakableItem::StaticClass(); \

#endif // Legend_NATIVE_DEFS

#ifdef NATIVES_ONLY
NATIVE_INFO(ADynamicBlockingVolume) GLegendADynamicBlockingVolumeNatives[] = 
{ 
	MAP_NATIVE(ADynamicBlockingVolume,execSetFaces)
	{NULL,NULL}
};
IMPLEMENT_NATIVE_HANDLER(Legend,ADynamicBlockingVolume);

#endif // NATIVES_ONLY
#endif // __STATIC_LINK

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_SIZE_NODIE(ADynamicBlockingVolume)
VERIFY_CLASS_SIZE_NODIE(ABreakableItem)
#endif // VERIFY_CLASS_SIZES
