/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#ifndef UI_API
#define UI_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern UI_API FName UI_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY


class UI_API UTexUIhook : public UTexModifier
{
public:
    FStringNoInit ComponentName;
    BITFIELD bRelative:1 GCC_PACK(4);
    BITFIELD bPan:1;
    BITFIELD bScale:1;
    FComponentHandle C GCC_PACK(4);
    FRectangle Ri;
    FRectangle Rf;
    FMatrix M;
    DECLARE_CLASS(UTexUIhook,UTexModifier,0,UI)
	// UTexModifier interface
	virtual FMatrix* GetMatrix(FLOAT TimeSeconds);
};


class UI_API UUIConsole : public UConsole
{
public:
    FStringNoInit Filename;
    FLOAT ScaleX;
    FLOAT ScaleY;
    FLOAT OffsetX;
    FLOAT OffsetY;
    BITFIELD bShift:1 GCC_PACK(4);
    BITFIELD bCtrl:1;
    BITFIELD bAlt:1;
    BITFIELD bHideUI:1;
    BITFIELD bRendering:1;
    FStringNoInit LastLevelAction GCC_PACK(4);
    INT FrameIndex;
    FComponentHandle Root;
    TArrayNoInit<class UUIHelper*> Helpers;
    TArrayNoInit<class UObject*> Assets;
    TArrayNoInit<FComponentHandle> LevelComponents;
    DECLARE_FUNCTION(execTimedMessage);
    DECLARE_FUNCTION(execGetComponentSize);
    DECLARE_FUNCTION(execSecondsToTime);
    DECLARE_FUNCTION(execGetClient);
    DECLARE_FUNCTION(execGetTimeSeconds);
    DECLARE_FUNCTION(execGetPlayerOwner);
    DECLARE_FUNCTION(execGetUIConsole);
    DECLARE_FUNCTION(execGetConsole);
    DECLARE_FUNCTION(execRemoveKeyEventListener);
    DECLARE_FUNCTION(execAddKeyEventListener);
    DECLARE_FUNCTION(execRemoveKeyListener);
    DECLARE_FUNCTION(execAddKeyListener);
    DECLARE_FUNCTION(execRemoveTickListener);
    DECLARE_FUNCTION(execAddTickListener);
    DECLARE_FUNCTION(execDispatchMessage);
    DECLARE_FUNCTION(execGetLooseComponents);
    DECLARE_FUNCTION(execFindLooseComponent);
    DECLARE_FUNCTION(execGetComponent);
    DECLARE_FUNCTION(execAddComponent);
    DECLARE_FUNCTION(execDestroyComponent);
    DECLARE_FUNCTION(execAddNewComponent);
    DECLARE_FUNCTION(execLoadComponent);
    DECLARE_FUNCTION(execSendEvent);
    DECLARE_FUNCTION(execUnRegisterRenderListener);
    DECLARE_FUNCTION(execRegisterRenderListener);
    DECLARE_FUNCTION(execAddWatch);
    DECLARE_FUNCTION(execGetInstance);
    DECLARE_CLASS(UUIConsole,UConsole,0|CLASS_Transient|CLASS_Config,UI)
    #include "UUIConsole.h"
};


class UI_API UUIHelper : public UObject
{
public:
    DECLARE_FUNCTION(execConsoleCommand);
    DECLARE_FUNCTION(execGetClient);
    DECLARE_FUNCTION(execGetTimeSeconds);
    DECLARE_FUNCTION(execGetPlayerOwner);
    DECLARE_FUNCTION(execGetUIConsole);
    DECLARE_FUNCTION(execGetConsole);
    DECLARE_CLASS(UUIHelper,UObject,0,UI)
    #include "UUIHelper.h"
};

#endif

AUTOGENERATE_FUNCTION(UUIConsole,-1,execTimedMessage);
AUTOGENERATE_FUNCTION(UUIConsole,-1,execGetComponentSize);
AUTOGENERATE_FUNCTION(UUIConsole,-1,execSecondsToTime);
AUTOGENERATE_FUNCTION(UUIConsole,-1,execGetClient);
AUTOGENERATE_FUNCTION(UUIConsole,-1,execGetTimeSeconds);
AUTOGENERATE_FUNCTION(UUIConsole,-1,execGetPlayerOwner);
AUTOGENERATE_FUNCTION(UUIConsole,-1,execGetUIConsole);
AUTOGENERATE_FUNCTION(UUIConsole,-1,execGetConsole);
AUTOGENERATE_FUNCTION(UUIConsole,-1,execRemoveKeyEventListener);
AUTOGENERATE_FUNCTION(UUIConsole,-1,execAddKeyEventListener);
AUTOGENERATE_FUNCTION(UUIConsole,-1,execRemoveKeyListener);
AUTOGENERATE_FUNCTION(UUIConsole,-1,execAddKeyListener);
AUTOGENERATE_FUNCTION(UUIConsole,-1,execRemoveTickListener);
AUTOGENERATE_FUNCTION(UUIConsole,-1,execAddTickListener);
AUTOGENERATE_FUNCTION(UUIConsole,-1,execDispatchMessage);
AUTOGENERATE_FUNCTION(UUIConsole,-1,execGetLooseComponents);
AUTOGENERATE_FUNCTION(UUIConsole,-1,execFindLooseComponent);
AUTOGENERATE_FUNCTION(UUIConsole,-1,execGetComponent);
AUTOGENERATE_FUNCTION(UUIConsole,-1,execAddComponent);
AUTOGENERATE_FUNCTION(UUIConsole,-1,execDestroyComponent);
AUTOGENERATE_FUNCTION(UUIConsole,-1,execAddNewComponent);
AUTOGENERATE_FUNCTION(UUIConsole,-1,execLoadComponent);
AUTOGENERATE_FUNCTION(UUIConsole,-1,execSendEvent);
AUTOGENERATE_FUNCTION(UUIConsole,-1,execUnRegisterRenderListener);
AUTOGENERATE_FUNCTION(UUIConsole,-1,execRegisterRenderListener);
AUTOGENERATE_FUNCTION(UUIConsole,-1,execAddWatch);
AUTOGENERATE_FUNCTION(UUIConsole,-1,execGetInstance);
AUTOGENERATE_FUNCTION(UUIHelper,-1,execConsoleCommand);
AUTOGENERATE_FUNCTION(UUIHelper,-1,execGetClient);
AUTOGENERATE_FUNCTION(UUIHelper,-1,execGetTimeSeconds);
AUTOGENERATE_FUNCTION(UUIHelper,-1,execGetPlayerOwner);
AUTOGENERATE_FUNCTION(UUIHelper,-1,execGetUIConsole);
AUTOGENERATE_FUNCTION(UUIHelper,-1,execGetConsole);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif

#if __STATIC_LINK
#ifndef UI_NATIVE_DEFS
#define UI_NATIVE_DEFS

DECLARE_NATIVE_TYPE(UI,UUIConsole);
DECLARE_NATIVE_TYPE(UI,UTexUIhook);
DECLARE_NATIVE_TYPE(UI,UUIHelper);

#define AUTO_INITIALIZE_REGISTRANTS_UI \
	UUIConsole::StaticClass(); \
	GNativeLookupFuncs[Lookup++] = &FindUIUUIConsoleNative; \
	UTexUIhook::StaticClass(); \
	UUIHelper::StaticClass(); \
	GNativeLookupFuncs[Lookup++] = &FindUIUUIHelperNative; \

#endif // UI_NATIVE_DEFS

#ifdef NATIVES_ONLY
NATIVE_INFO(UUIConsole) GUIUUIConsoleNatives[] = 
{ 
	MAP_NATIVE(UUIConsole,execTimedMessage)
	MAP_NATIVE(UUIConsole,execGetComponentSize)
	MAP_NATIVE(UUIConsole,execSecondsToTime)
	MAP_NATIVE(UUIConsole,execGetClient)
	MAP_NATIVE(UUIConsole,execGetTimeSeconds)
	MAP_NATIVE(UUIConsole,execGetPlayerOwner)
	MAP_NATIVE(UUIConsole,execGetUIConsole)
	MAP_NATIVE(UUIConsole,execGetConsole)
	MAP_NATIVE(UUIConsole,execRemoveKeyEventListener)
	MAP_NATIVE(UUIConsole,execAddKeyEventListener)
	MAP_NATIVE(UUIConsole,execRemoveKeyListener)
	MAP_NATIVE(UUIConsole,execAddKeyListener)
	MAP_NATIVE(UUIConsole,execRemoveTickListener)
	MAP_NATIVE(UUIConsole,execAddTickListener)
	MAP_NATIVE(UUIConsole,execDispatchMessage)
	MAP_NATIVE(UUIConsole,execGetLooseComponents)
	MAP_NATIVE(UUIConsole,execFindLooseComponent)
	MAP_NATIVE(UUIConsole,execGetComponent)
	MAP_NATIVE(UUIConsole,execAddComponent)
	MAP_NATIVE(UUIConsole,execDestroyComponent)
	MAP_NATIVE(UUIConsole,execAddNewComponent)
	MAP_NATIVE(UUIConsole,execLoadComponent)
	MAP_NATIVE(UUIConsole,execSendEvent)
	MAP_NATIVE(UUIConsole,execUnRegisterRenderListener)
	MAP_NATIVE(UUIConsole,execRegisterRenderListener)
	MAP_NATIVE(UUIConsole,execAddWatch)
	MAP_NATIVE(UUIConsole,execGetInstance)
	{NULL,NULL}
};
IMPLEMENT_NATIVE_HANDLER(UI,UUIConsole);

NATIVE_INFO(UUIHelper) GUIUUIHelperNatives[] = 
{ 
	MAP_NATIVE(UUIHelper,execConsoleCommand)
	MAP_NATIVE(UUIHelper,execGetClient)
	MAP_NATIVE(UUIHelper,execGetTimeSeconds)
	MAP_NATIVE(UUIHelper,execGetPlayerOwner)
	MAP_NATIVE(UUIHelper,execGetUIConsole)
	MAP_NATIVE(UUIHelper,execGetConsole)
	{NULL,NULL}
};
IMPLEMENT_NATIVE_HANDLER(UI,UUIHelper);

#endif // NATIVES_ONLY
#endif // __STATIC_LINK

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_SIZE_NODIE(UUIConsole)
VERIFY_CLASS_SIZE_NODIE(UTexUIhook)
VERIFY_CLASS_SIZE_NODIE(UUIHelper)
#endif // VERIFY_CLASS_SIZES
